NUMPY 

* It is a library that allows us to use very large matrices, arrays, lists quickly.

* It simplifies operations and allows us to calculate the averages and sums of columns without any hassle when dealing with data sets.





**Numpy Library Add**

In [1]:
import numpy as np

 A Numpy Array Create 

 Array is like Python's list.

 Code Logic: We have already entered a list in the np.array () function, we converted the List in Python to a numpy array.

In [2]:
array = np.array([1,2,3,4])
print(array)


[1 2 3 4]


 We created a vector (1,4) of 1 row and 4 columns

**Find the size of the array**

ndarray.ndim
the number of axes (dimensions) of the array.



In [3]:
print(array.ndim) #it is one dimensional

1


In [4]:
array2 = np.array([[1,2],[3,4]])
print(array2.ndim)  # it is two dimensional

2


Finding the number of rows and columns of the array

In [5]:
print(array.shape) #A one-dimensional array (vector) of four elements

(4,)


In [6]:
print(array2.shape) #A 2 dimensional array (matrix) consisting of 2 rows and 2 columns


(2, 2)


**Changing the number of rows and columns of the array.**

In [7]:
print(array.reshape(1,4)) #1 row became 4 columns
print(array.reshape(2,2)) #2 row became 2 columns

[[1 2 3 4]]
[[1 2]
 [3 4]]


# Creating numpy array in certain range

In [8]:
array3 = np.arange(0,10,3) #np.arange(start, end, number of steps) used in the form
print(array3)  #1 dimensional array of 4 elements.

[0 3 6 9]


In [9]:
array4 = np.arange(10) #We create arrays between 0 and 10, not including 10.
print(array4) # 1 dimensional array of 10 elements.



[0 1 2 3 4 5 6 7 8 9]


**Selecting the elements of the array**

In [10]:
array5 = np.arange(10)  #1 dimensional array of 10 elements

array5 = array5.reshape(5,2) #5 rows have been transformed into an array of 2 columns.

Original of array: ", array5, sep =" \ n "

In [11]:
firstRow = array5[0]  # Let's select the 1st line of the array
print("#1st line of the array: ", firstRow, sep="\n")


#1st line of the array: 
[0 1]


Let's Choose Row 1 and 2 of the Series

In [15]:
firstAndSecondRow = array5[0:2] # From 0 to 2, 2 is not included.
print("Row 1 and 2 of Series:" , firstAndSecondRow , sep="\n")


Row 1 and 2 of Series:
[[0 1]
 [2 3]]


Selecting any element from the array

In [18]:
print("The value in the 3rd row and 1st column of the array : ", array5[3:1],  sep=" ", end= "\n")  #We selected the 1st element of the 3rd row

The value in the 3rd row and 1st column of the array :  []


Let's choose column 1

In [ ]:
firstColumn = array5[:,0] 

print("Column 1 of the Series " : ", firstColumn,sep="\n")

Let's choose columns 1 and 2

In [ ]:
firstAndSecondColumn = array5[:,0:2]

Reverse the sequence

In [ ]:
array6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])   # Created a 1-dimensional array with 10 elements
array6 = array6.reshape(5,2)                        

print("Our Series : ", array6, sep="\n")
array6 = array6[::-1]                               # Select all rows and columns.Multiply by -1 so the array is written backwards
print("Our Inverted Array: ",array6,sep="\n")


**Creating a zero matrix.**

In [ ]:
 
 zerosArray = np.zeros((5,4)) #Creating a 0 matrix with 5 rows and 4 columns

 print("Creating a 0 matrix with 5 rows and 4 columns: ", zerosArray, sep="\n")

**Creating The Ones Matrix**

In [ ]:
onesArray = np.ones((5,4))  #The ones matrix consisting of 5 rows and 4 columns was created
print(" The ones matrix consisting of 5 rows and 4 columns was created : ", onesArray,sep ="\n")


**Creating The Unit Matrix**

In [ ]:
unitArray = np.eye(4) 
print(" Unit of 4 rows and 4 columns matrix :" , unitArray , sep="\n" )

**Combining Matrices**

In [ ]:
array7 = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
array8 = np.array(["a","b","c","d","e","f","g","w","u","r"])

array7 = array7.reshape(5,2)
array8 = array8.reshape(5,2)

**Let's Join The Rows**

In [ ]:
print(np.concatenate([array7,array8],axis=0),sep="\n")

**Let's Join The Columns**

In [ ]:
print(np.concatenate([array7,array8],axis=1))

**Calculating Max and Min Values**

In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print("Our Array : ", numpy_array, sep="\n")

**Finding The Max Value in The Array**

In [ ]:
print("MAX : ", numpy_array.max())

**Finding The Min Value in The Array**

In [ ]:
print("MIN: ", numpy_array.min())

**Collect The Whole Series**

In [ ]:
print("SUM: ", numpy_array.sum())

**Sum Of Rows**

In [ ]:
print("Sum Of Rows : ",numpy_array.sum(axis = 1))

**Sum Of Columns**

In [ ]:
print("Sum Of Columns: ",numpy_array.sum(axis = 0))

**Arithmetic Operations on Matrices**

In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
print(numpy_array)

**Addition**

In [ ]:
print(numpy_array + numpy_array)

**Subtraction**

In [ ]:
print(numpy_array - numpy_array)

**Multiplication**

In [ ]:
print(numpy_array * numpy_array)


**Division**

In [ ]:
print(numpy_array / numpy_array)


**We Added 5 to Each Value**

In [ ]:
print(numpy_array + 5)

**We Multiplied Each Value by 2**

In [ ]:
print(numpy_array * 2)

**Matrices Multiplied**

In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array1 = numpy_array.reshape(5,2)
numpy_array2 = numpy_array.reshape(2,5)
print(np.dot(numpy_array1,numpy_array2))

**Transposition of The Matrix**

In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)
print("------------------------ Transposed ----------------------")
print(numpy_array.T)

**Condition Statements in Numpy**

In [ ]:
# Displays those greater than and equal to 5 in the numpy array as True.

numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
boolean_array = numpy_array >= 5
print(boolean_array)